### ISSUE TITLE
Dependency conflict when having http package version 1.2.1

### ISSUE THREAD

**Issue by fengjiongmax** [sudame/dart-rss#50]
Hello, I'm trying to have this package installed along with [http](https://pub.dev/packages/http), but the `flutter pub add` command shows the following error message:
```
$ flutter pub add dart_rss
The current Dart SDK version is 3.3.0.

Because dart_rss >=2.0.0 depends on http ^0.13.0 and dart_rss <2.0.0 doesn't support null safety, every version of dart_rss
  requires http ^0.13.0.
So, because castnugget depends on both http ^1.2.1 and dart_rss any, version solving failed.

The lower bound of "sdk: '>=2.6.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
```
my `dependencies` and `dev_dependencies`:
```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  xml: ^6.5.0
  get_it: ^7.6.7
  path_provider: ^2.1.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.1.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

```
